# 服务配置
server:
  # 监听地址
  ip: 0.0.0.0
  # 监听端口
  port: 9000

# 日志配置
tracing:
  # 日志级别
  max_level: info
  # 是否使用ANSI
  ansi: true
  # 是否显示级别
  level: true
  # 是否显示文件
  file: true
  # 是否显示线程名称
  thread_names: true
  # 是否显示行号
  line_number: true

# 服务发现
discovery:
  # 内置服务发现实现，通过配置声明服务地址
  - kind: Builtin
    args:
      # 服务名
      server: server1
      # 服务节点
      uris:
        - 127.0.0.1:9000
        - 127.0.0.1:9001
        - 127.0.0.1:9002
      # 检测是否可用间隔时间
      interval: 10
      # 负载策略
      lb: Random
  

# 路由配置
router:
  # 请求日志
  trace:
    # 级别
    level: debug
    # 是否输出请求头
    include_headers: true
  # 全局配置
  global:
    # 全局的Layer
    layers:
      - Cors
  # 路由列表
  routes:
    - id: static
      # Matchers
      matchers:
        - Method=GET
      # Layers
      layers:
        - RateLimit=Break,10,10
      # Service
      service: Static=examples/resources

    - id: proxy
      # Matchers
      matchers:
        - Path=/proxy
      # Layers
      layers:
        - PathStrip=1
      # Service
      service: Proxy=http://server1
